spring:
  application:
    name: e-commerce
#============================================================================#
# Default profile configuration properties
#============================================================================#
  datasource:
    generate-unique-name: false
    name: e_commerce_db
    url: jdbc:mysql://localhost/e-commerce
    username: e-user
    password:
  jpa:
    properties:
      show-sql: false
    hibernate:
      ddl-auto: create
---
#============================================================================#
# Dev profile configuration properties
#============================================================================#
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
  logging:
    root:
      level: DEBUG