spring:
  application:
    name: e-commerce
#============================================================================#
# Default profile configuration properties
#============================================================================#
  datasource:
    generate-unique-name: false
    name: e_commerce_db
    url: ${E_COMMERCE_DB_URL}
    username: ${E_COMMERCE_DB_USERNAME}
    password: ${E_COMMERCE_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true